spring.application.productName=project
# MySQL DB 연결 설정
spring.datasource.url=jdbc:mysql://localhost:3306/shopping_db
spring.datasource.username=root
spring.datasource.password=a1402a8am16oje
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA SQL 로그 확인
spring.jpa.show-sql=true
# SQL문 줄 바꿈
spring.jpa.properties.hibernate.format_sql=true
# Entity 기준 테이블 자동 생성/수정
spring.jpa.hibernate.ddl-auto=update
# JWT 토큰 설정
jwt.secret=U3ByaW5nQm9vdFNob3BwaW5nQXBpSldUU2VjcmV0S2V5
jwt.access.expiration=3600000
jwt.refresh.expiration=86400000